### PR TITLE
Review title hierarchy

### PR DESCRIPTION
**Pull request by martgnz**
Connects to #462.

### What does this PR do?
This PR improves the title hierarchy of Gobierto, ensuring every tag is consistent, marking a clear structure of the modules.

## How should this be manually tested?
You can use the [tota11y](https://khan.github.io/tota11y/) bookmarklet to review the header structure on every page of Gobierto.

### CODE REVIEW

**Review by ferblape — APPROVED** [review]
Looks OK to me

**Review by ferblape — CHANGES_REQUESTED** [review]
@martgnz there are a couple of issues with the headings in the blog page and statements page of a person: http://dival.gobify.net/cargos-y-agendas/cargos/5/bienes-y-actividades and http://dival.gobify.net/cargos-y-agendas/cargos/5/blog/posts

**Comment by martgnz** [comment]
Now the styles are more consistent 👍

**Review by ferblape — APPROVED** [review]
👍

**Pull request merged**
