### PR TITLE
Remove cloudinary service

### LINKED ISSUE #4199: Remove Cloudinary
Analyze if we can get rid of the Cloudinary service. Review what is currently doing, and see if we can use some local JS to do the same.

If I'm not wrong, it is only used to crop and resize images for https://gobierto.readme.io/docs/altos-cargos-y-agendas#crear-y-editar-una-persona

Related: https://appsignal.com/populate/sites/5ebb88520264445dc7e68b5c/exceptions/incidents/4244/samples/timestamp/2024-02-12T08:46:02Z

### PR DESCRIPTION
**Pull request by Crashillo**
Closes #4199

## :v: What does this PR do?
Deprecate Cloudinary service to replace it with [Cropperjs](https://fengyuanchen.github.io/cropperjs/v2/). Clean of the related files

https://madrid.gobify.net/admin/people/people/1363/edit

### CODE REVIEW

**Comment by furilo** [comment]
@aramollis can you test this? Image uploads for Agendas etc should work as usual.

**Comment by aramollis** [comment]
> @aramollis can you test this? Image uploads for Agendas etc should work as usual.

I checked (Agenda & Plans)
- Works as expected for single image field (img avatar agenda, simple img custom field for plans)
- [x] Cropping not working for multiple custom field in Plans (tried in this [project](https://madrid.gobify.net/planes/plan-de-gobierno/2020/proyecto/9435)) I tried to crop all images but multiple field img show full img.
Captura de Pantalla 2024-02-26 a les 18 14 56

**Comment by Crashillo** [comment]
Solving the multiple images issue made me sweat really hard 😖😖😖 Gosssssh!

**Comment by ferblape** [comment]
@aramollis could you check again?

**Review by aramollis — APPROVED** [review]
works as expected. 👌👏

**Pull request merged**
