### PR TITLE
2387 - Improve horiz/vert content disposition for SlickGrid

### LINKED ISSUE #2387: Improve dimensions of Slickgrid-related plugins
- [ ] Avoid the empty space on the right:

image

Avoid too much empty "vertical" space when there are few rows in the table. The objective should be:

- [ ] We never show a vertical scrolling bar
- [ ] When the table is almost emtpy there's not too much empty space. Right now it's fixed via plugin JS to 500px weight. Test with 200.

### PR DESCRIPTION
**Pull request by amiedes**
Closes #2387 

## :v: What does this PR do?

Improves horizontal and vertical content disposition for Slickgrid tables.

## :mag: How should this be manually tested?

...

### Before this PR

image

### After this PR

When the table is empty:

image

If you add new rows, the height is readjusted:

add_rows

For the indicators table, which has variable width, once the columns don't fit in the page anymore a horizontal scrollbar appears:

horizontal_scrolling

### CODE REVIEW

**Comment by amiedes** [comment]
There's a styling issue when expanding the selec2 from the last row:

image

@Crashillo can you fix this? Feel free to add commits to this PR.

You can see it in action in http://talavan.gobify.net/admin/plans/15/projects/8687/edit, or in local in happens also in http://madrid.gobierto.test/admin/plans/28856268/projects/252926840/edit

**Comment by Crashillo** [comment]
@amiedes it's not straightforward. select2 container is calculated via javascript, based on how high the selector is. Perhaps, force the selector to fit the cell height. The coolest way would be handling the absolute elements, but there's a lot of wrapped elements each other quite hard to deal with.

Please, make an issue to take into account in future iterations

**Comment by ferblape** [comment]
Ok, let's create other issue to fix the styles. @amiedes / @entantoencuanto  feel free to merge this PR when you can, code looks good.

**Comment by amiedes** [comment]
Created follow-up issue for the styles #2425

**Pull request merged**
