### PR TITLE
Site location autocomplete control against municipalities endpoint

### PR DESCRIPTION
**Pull request by danguita**
Connects to #38.

### What does this PR do?

First of all, it applies a complete cleanup on the Admin namespace layout by creating specific manifest files that don't load any (hopefully) unused vendors or components. Right now there's some duplication in user (default) and Admin namespaces so it's quite difficult to detect what is actually being used in each one. I'd say it's a good starting point to keep things clean from now on.

Secondly, it implements a Site location selection user control based on jquery-ui's autocomplete component. It performs a request to an external endpoint that provides a structured source of municipalities to choose from. As part of the user control implementation, the form now sets the `Site#municipality_id` attribute to keep an internal reference to the selected municipality regardless the location field content.

### How should this be manually tested?

The Site location autocomplete user control should be available in both new and edit actions, so just check that the location field is being autocompleted in http://gobierto.dev/admin/sites/new and any of the `http://gobierto.dev/admin/sites/<site_id>/edit` URLs.

Regarding the Admin cleanup, it'd be great to do a quick tour on every Admin section to be sure everything is still working. Integration tests are passing but the coverage isn't still specially high BTW.
### Final notes

How about generating a new auth token for the `http://gobierto.dev` Origin so that we can be consistent in our development environments? /cc @ferblape

### CODE REVIEW

**Comment by ferblape** [comment]
Agreed, we need a token for the development environment. I'll take care.

**Comment by danguita** [comment]
I've just synced this branch with `master` and recovered some missing assets in the Admin namespace. Sorry for the noise, I wanted to make sure everything works as expected.

**Comment by ferblape** [comment]
Merging this one. I have removed the credentials from the example env file, I'll give you new ones.

**Comment by danguita** [comment]
@ferblape 👌 Go for it! Thanks for taking care.

**Pull request merged**
