### PR TITLE
Attachments in events

### LINKED ISSUE #1158: Attachments on events are not displayed
Attachments on events are not rendered. In the sandbox there wasn't design for this either http://madrid.gobierto.dev/sandbox/participation_agenda_event.html

Maybe we could do the same as in documents and render the attachments in the sidebar: http://madrid.gobierto.dev/sandbox/participation_news_item.html

### PR DESCRIPTION
**Pull request by apradillap**
Closes #1158 and https://github.com/PopulateTools/issues/issues/149

### What does this PR do?

- An event can have more than one associated document.
- Attachment it's showing in the event
- The associated documents appear in processes documents section.

### How should this be manually tested?

You can associate a document with a person event or process event:
captura de pantalla 2017-11-23 a las 15 20 38

captura de pantalla 2017-11-23 a las 15 20 16

### Migrations

I have checked the staging and production environments and there are only 4 documents associated with events. In staging with the events:
7363,7552,7578 y 7736. I have saved the documents to attach them

### Pending

I have observed in testing, missing pages for events associated with Site or Participation
https://github.com/PopulateTools/gobierto/issues/932

### CODE REVIEW

**Comment by apradillap** [comment]
Migrated staging documents

**Review by ferblape — APPROVED** [review]
Good to me!

**Comment by furilo** [comment]
Wait for some markup changes.

**Review by furilo — APPROVED** [review]

**Comment by apradillap** [comment]
Ready to merge!

**Pull request merged**
