### PR TITLE
ElasticSearch fake data

### PR DESCRIPTION
**Pull request by ferblape**
This PR takes care of #8 

Now you can run `script/test` and ES indices and fake data are loaded. I have also added a very simple test that loads the home of the budgets module.

`script/setup` will also run some data for the development environment, for the municipality Madrid.

### CODE REVIEW

**Comment by ferblape** [comment]
Ready

**Comment by danguita** [comment]
Hey @ferblape, I've just updated the `gobierto_budgets:fixtures:load` task to perform bulk Elasticsearch operations at https://github.com/PopulateTools/gobierto-dev/pull/9/commits/ca641722edeb8e012ad71ef123908e74293e3c36. Could you please take a look? The rest looks great to me 👍

**Comment by danguita** [comment]
Tests are passing 🚀 

```
== Importing categories ==
== Importing budgets for place Madrid in 2015 ==
== Importing budgets for place Madrid in 2016 ==
Started with run options --seed 28780

MetaWelcomeControllerTest
  test_index                                                      PASS (0.17s)

GobiertoBudgets::HomePageTest
  test_greeting                                                   PASS (1.08s)

HomePageTest
  test_greeting                                                   PASS (0.17s)

SiteTest
  test_valid                                                      PASS (0.02s)

Finished in 1.44986s
4 tests, 7 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ferblape** [comment]
Looking great

**Pull request merged**
