### PR TITLE
Sourcemaps in rollbars

### PR DESCRIPTION
**Pull request by Crashillo**
Enables sourcemaps in rollbar reports

### CODE REVIEW

**Comment by ferblape** [comment]
Sourcemaps are not visible yet in staging: https://rollbar.com/Populate/gobierto/items/2808/

**Comment by Crashillo** [comment]
Hmmmm, it's odd. Look at this rollbar https://rollbar.com/Populate/gobierto/items/2809/. It does have the sourcemaps, even it's the same site. 😕 🤔

**Comment by amiedes** [comment]
Are we missing this?

> You'll need to generate source maps, if you aren't already. This can be done using tools like the Closure Compiler or UglifyJS 2.

Source: https://docs.rollbar.com/docs/source-maps#section-source-map-requirements

**Comment by Crashillo** [comment]
Nope, we actually have sourcemaps, webpack takes care of it. You might check that out, open devtools>sources or debugger and you'll find an item at the left sidebar called Webpack (or similar). There you'll find the original javascript code

**Comment by Crashillo** [comment]
I'd let this go on, meanwhile we're watching if the next rollbar errors come full-informed

**Pull request merged**
