### PR TITLE
3826 remove module budgets consultations

### PR DESCRIPTION
**Pull request by stbnrivas**
Closes #N

## :v: What does this PR do?

remove module budget consultations

## :shipit: Does this PR changes any configuration file?

- [ ] new environment variable in `.env.example`?
- [ ] new entry in `config/application.yml`?
- [ ] new entry in `config/secrets.yml`?

(Changes in these files might need to update the role in Ansible)

## :book: Does this PR require updating the documentation?

- [ ] new site configuration variable?
- [ ] new site template?
- [ ] new module/submodule settings?
- [ ] significant changes in some feature?

### CODE REVIEW

**Comment by stbnrivas** [comment]
@ferblape why these test files are defined as a module instead of test case?

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/test/support/concerns/user/subscribable_test.rb#L3-L44

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/test/support/concerns/user/subscriber_test.rb#L3-L51

should I normalize like below, or I am missing something?

```
require "test_helper"
class User::SubscribableTest < ActiveSupport::TestCase
...
end 


require "test_helper"
class User::SubscriberTest < ActiveSupport::TestCase
...
end 
```

thx

**Comment by stbnrivas** [comment]
@ferblape I have some questions: 

1. into model user the attribute referrer_entity entity was used only to set `GobiertoBudgetConsultations::Consultation`, so without budget consultation I will removed

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/app/controllers/user/custom_sessions_controller.rb#L106-L112

I'm confused becuse it is related to auth_strategies at https://github.com/PopulateTools/gobierto/tree/master/vendor/auth_strategies/null_strategy

should delete?  or I'm missing something? 




2. about census_verification and id_number ... 

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/app/models/user.rb#L13-L14

imho without GobiertoBudgetConsultation::Consultation 

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/app/forms/user/confirmation_form.rb#L41-L43

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/app/forms/user/confirmation_form.rb#L124-L144

I think that census verification can be delete into this PR because was used only into budget consultation. wdyta? or I'm missing something?


thx

**Comment by ferblape** [comment]
1. Remove the internal code but keep the method, because it's useful to be redirected after signup. You can leave a comment inside:

```
# Example:
# if request.referrer.include?("url-path")
#   "GobiertoModuleName::ControllerName"
# end
```

2. If possible I'd try to keep it, it could be useful in the future

**Comment by stbnrivas** [comment]
Sorry, about question 1 I need confirmation Does referrer_url is being used to redirect after after sign_up ? 
some examples from staging below:

referrer_url    | http://${staging-url}/consultas_presupuestos/3/partidas
referrer_entity | GobiertoBudgetConsultations::Consultation

referrer_url    | http://${staging-url}/consultas_presupuestos/3/partidas
referrer_entity | GobiertoBudgetConsultations::Consultation

referrer_url    | 
referrer_entity | 

referrer_url    | http://${staging-url}/consultas_presupuestos/3/partidas
referrer_entity | GobiertoBudgetConsultations::Consultation

referrer_url    | http://${staging-url}/cargos-y-agendas
referrer_entity | 


referrer_entity is used for specific require verification, I can keeping and do a comment to clarify

https://github.com/PopulateTools/gobierto/blob/91e9cfee11ab6bb55990e9ed38dae1a5612e6391/app/forms/user/confirmation_form.rb#L41-L43


thx

**Comment by ferblape** [comment]
I wasn't sure, but yes, it's a kind of step after signup.

You can rewrite that method to:

```
 def require_user_verification? 
    # Temporary
    false
  end
```

**Comment by stbnrivas** [comment]
So I'm not really sure about. Just to say that I preferred to keep it

https://github.com/PopulateTools/gobierto/blob/master/test/forms/gobierto_admin/census_import_form_test.rb

https://github.com/PopulateTools/gobierto/blob/master/test/fixtures/files/census.csv

**Pull request merged**
