### PR TITLE
Search results sandbox

### LINKED ISSUE #214: Menu animation in Firefox
The animation is working badly.

### PR DESCRIPTION
**Pull request by furilo**
Connects to #299, #214 

### What does this PR do?

Provides the sandbox for the search box and social links in the header, and a basic search results page: http://madrid.gobierto.dev/sandbox/search_results - And fixes #214 

Pending: 
- [x] I think this is using the right layout, but there is an HTML bug with the header http://madrid.gobierto.dev/indicadores
- [x] Integrate social links in the header (they can take the OG properties of the header)
- [x] Integrate search results page
- [x] Integrate search results box in header

### CODE REVIEW

**Review by ferblape — APPROVED** [review]
👍

**Comment by ferblape** [comment]
@furilo this is ready and can be checked in staging.

A couple of things:

- [x] the results are included in the layout in `<div id="search_results" class="search_result_list"></div>`
- [ ] we are stripping the HTML of the bios and items descriptions. I'm not very happy with the results.

**Comment by furilo** [comment]
> we are stripping the HTML of the bios and items descriptions. I'm not very happy with the results.

Why?

**Comment by ferblape** [comment]
Because the HTML tags are stripped, and we lose line breaks. See this item 

screen shot 2017-02-10 at 15 03 27

For the moment is fine, let's see how it goes.

**Pull request merged**
