### PR TITLE
Adding missing data declaration. Fixing test with it.

### LINKED ISSUE #3088: GobiertoDashboards::DashboardsContractsTest#test_contracts
```
GobiertoDashboards::DashboardsContractsTest#test_contracts [**************/gobierto/test/integration/gobierto_dashboards/dashboards_contracts_test.rb:135]
 
Minitest::Assertion: Expected false to be truthy.
```

### PR DESCRIPTION
**Pull request by eltercero**
Closes #3088

## :v: What does this PR do?

Fixes a failing test from the dashboards module.

## :shipit: Does this PR changes any configuration file?

No

## :book: Does this PR require updating the documentation?

No

### CODE REVIEW

**Comment by ferblape** [comment]
I'm seeing tests failing in my local environment. 

Sometimes 2:

```
Failure:
GobiertoDashboards::DashboardsContractsTest#test_summary [/Users/fernando/proyectos/gobierto/test/integration/gobierto_dashboards/dashboards_contracts_test.rb:68]
Minitest::Assertion: Expected false to be truthy.

Failure:
GobiertoDashboards::DashboardsContractsTest#test_tenders [/Users/fernando/proyectos/gobierto/test/integration/gobierto_dashboards/dashboards_contracts_test.rb:180]
Minitest::Assertion: Expected false to be truthy.
```

And sometimes 3:

```
Failure:
GobiertoDashboards::DashboardsContractsTest#test_summary [/Users/fernando/proyectos/gobierto/test/integration/gobierto_dashboards/dashboards_contracts_test.rb:68]
Minitest::Assertion: Expected false to be truthy.

Failure:
GobiertoDashboards::DashboardsContractsTest#test_tenders [/Users/fernando/proyectos/gobierto/test/integration/gobierto_dashboards/dashboards_contracts_test.rb:180]
Minitest::Assertion: Expected false to be truthy.

Failure:
GobiertoDashboards::DashboardsContractsTest#test_contracts [/Users/fernando/proyectos/gobierto/test/integration/gobierto_dashboards/dashboards_contracts_test.rb:94]
Minitest::Assertion: Expected false to be truthy.
```

**Comment by eltercero** [comment]
@ferblape I can't seem to reproduce those failures, it always passes all the tests for me. Is this the first time you run them? If not, have they passed before?

**Comment by ferblape** [comment]
Yes, it's the first time I run them. I've just checked out your branch and executed them

**Comment by eltercero** [comment]
@ferblape so, this test was fixed after merging #3063 (I noticed the missing data declaration there a few days ago 3488a276e4da3002b4aef34d3fda4d8240591882), so this PR is not really neccesary anymore. Tests seems to pass now in master.

About the failures, sometimes the first couple of times (usually just the first time) they fail because the assets didn't fully compile for the test (it happnes to me too). Could that be the case?

**Comment by ferblape** [comment]
Maybe, if master is fine now, then let's close this. Thanks!

**Pull request closed without merging**
