### PR TITLE
CSV plans importer

### PR DESCRIPTION
**Pull request by entantoencuanto**
Closes [#250](https://github.com/PopulateTools/issues/issues/250)

## :v: What does this PR do?
Allows to load plans data from a csv file in admin

## :mag: How should this be manually tested?
Go to edition of an existing plan and select data tab. Upload a valid csv file.
The plan must have defined in configuration the names for the different categories levels to avoid errors trying to display plan data.

### After this PR
screen shot 2018-07-06 at 12 08 19
screen shot 2018-07-06 at 12 09 02

## :shipit: Does this PR changes any configuration file?
No

### CODE REVIEW

**Comment by ferblape** [comment]
I know it's still WIP but I have just imported Madrid plan in [Madrid site](http://madrid.gobify.net/admin/plans/6/data) and I got this error: https://rollbar.com/Populate/gobierto/items/1144/

This is the file, which I think is correct: http://blat-public.s3.amazonaws.com/plan-madrid.csv

**Comment by ferblape** [comment]
Importer works fine. We follow in #1768

**Review by ferblape — CHANGES_REQUESTED** [review]
Just one thing, validations are not working very well in Status column. Check with this CSV: http://blat-public.s3.amazonaws.com/plan-madrid-wrong.csv

**Comment by entantoencuanto** [comment]
I have added a validation for each row checking that `Node.Title` and `Node.Status` aren't blank if a node must be created (a node is expected to be created if there is at least one `Node...` column with data, otherwise only the categories are created). Also a validation error is raised if any category (or node if it has to be created) does not pass validations. In any case, `Category` and `Node` models do not seem to have validations, I'll review that.

**Comment by ferblape** [comment]
👍

**Pull request merged**
