### PR TITLE
Fix mouse events

### LINKED ISSUE #1944: d3.event on lineas_tabla chart not working
Mouse events on the chart are ignored, throwing an error

### PR DESCRIPTION
**Pull request by Crashillo**
Closes #1944 

## :v: What does this PR do?
Fix an error thrown by d3.event, whose failure breaks a chart feature

### Pending
Same behaviour on mouseover but the linecharts, not the table.

### Before this PR
imagen

### After this PR
Notice the opacity of the lines and points
imagen

### CODE REVIEW

**Comment by ferblape** [comment]
In Mataró staging, after deploying again, I still can see the error:

screen shot 2018-10-20 at 10 05 05

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn't, it's, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn't, it's, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn't, it's, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn't, it's, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn't, it's, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn’t, it’s, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn’t, it’s, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Not able to reproduce. Tested in mataro.gobify on Firefox, Chrome and Safari, working as expected. Did the lines of the contiguous chart fade out? If didn’t, it’s, perhaps, cached. 😕

**Comment by Crashillo** [comment]
Ok, now the chart mouseover is working properly again. 🎉

**Pull request merged**
