### PR TITLE
Migrate to esbuild

### PR DESCRIPTION
**Pull request by Crashillo**
Closes https://github.com/PopulateTools/issues/issues/1980
Related https://github.com/PopulateTools/gobierto-gencat-engine/pull/31

### CODE REVIEW

**Comment by Crashillo** [comment]
Well, it looks like it's ready to be merged. The pending stuff (available [here](https://docs.google.com/document/d/1WUsc0CdulfmSAj5gGMxi690SQa4gGM9q2Kz42mD3sLU/edit)) was done, including the most up-to-date esbuild version (it can be copied to gobierto-contratos).

Since this PR is really huge, desiderable things pointed in the previous link, should be done in different pull requests.

**Comment by ferblape** [comment]
I've done a deep review in Mataro, Esplugues and Getafe sites which have all modules enabled combining all of them. I've just found a couple of issues in Mataro visualizations:

- https://mataro.gobify.net/visualizaciones/deuda
- https://mataro.gobify.net/visualizaciones/costes

Both visualizations show the loading message and never disappears

**Comment by ferblape** [comment]
The costs visualization fails when you change the year https://mataro.gobify.net/visualizaciones/costes/2020

The debt visualization is fixed ✅

**Comment by Crashillo** [comment]
Solved and deployed, that required further analysis

**Pull request merged**
