### PR TITLE
[WIP] 2995 dashboards contracts

### LINKED ISSUE #2995: Create Gobierto dashboards module
Following the guide [developing a Gobierto module](https://gobierto.readme.io/docs/developing-a-new-module-of-gobierto), create the new module Gobierto Dashboards. This module will allow us to create dashboards and visualizations.

For the moment we'll implement the contracts/tenders visualization. 

- Mockup: https://www.figma.com/proto/gyMSROblmDqjkKt1TT8BcL5G/Gobierto-%2F-Contratos-Subvenciones?node-id=247%3A0&viewport=607%2C-881%2C0.25&scaling=min-zoom
- Basic HTML started in #3015 (this issue can be implemented in that branch)

Some features of the module:

- the name of the module will be Gobierto Dashboards
- it'll implement a main controller, where each action will be a dashboard
- the module won't have models, it'll use external data resources, such as CSVs or API endpoints
- the module configuration will allow to specify the configuration of each dashboard
- each module will have it's own JS controller
- the dashboards will be available in `/dashboards/` route. I.e: `/dashboards/contratos`

Checks to consider this issue completed:

- the code of the module should be added to the repository
- there will be a first dashboard named "contracts"
- it should be possible for admins to activate it
- a fake home should be visible with no content. For the moment it won't appear in the navigation menu, it will be accessible only using the URL

### PR DESCRIPTION
**Pull request by furilo**
Closes #2995 

## :shipit: Does this PR changes any configuration file?

- [ ] new environment variable in `.env.example`?
- [ ] new entry in `config/application.yml`?
- [ ] new entry in `config/secrets.yml`?

(Changes in these files might need to update the role in Ansible)

## :book: Does this PR require updating the documentation?

- [ ] new site configuration variable?
- [ ] new site template?
- [ ] new module/submodule settings?
- [ ] significant changes in some feature?

### CODE REVIEW

**Comment by ferblape** [comment]
@furilo rewriten last commit to remove changes in `db/schema.rb`

**Comment by furilo** [comment]
>
> @furilo <https://github.com/furilo> rewriten last commit to remove
> changes in db/schema.rb
>
 Sorry. This always happen to me when I pull changes, I _almost_ always
remeber to checkout the file again. How should I avoid it?

**Comment by ferblape** [comment]
If you see there are changes in the schema.rb you need to run `bin/rails db:drop db:setup` to reset your local database in the current branch to match the schema of the branch

**Comment by ferblape** [comment]
@eltercero please rebase/update your branch to incorporate the templates from the sandbox

**Comment by eltercero** [comment]
@ferblape done!

**Pull request merged**
