### PR TITLE
Site execution page

### PR DESCRIPTION
**Pull request by ferblape**
This PR implements #240 and #244

### CODE REVIEW

**Comment by furilo** [comment]
Take a look!

**Comment by ferblape** [comment]
I have fixed the current year mark in the graphics. I only miss the year breadcrumb.

**Comment by ferblape** [comment]
screen shot 2016-09-14 at 18 23 33

I have added the year picker. Maybe it would fit better in the heading "Desviación de los ingresos en <year>" but we can iterate later.

Please, review and confirm we can release it.

**Comment by furilo** [comment]
Good for me

**Pull request merged**
