### PR TITLE
Set initialization vars AFTER footer

### PR DESCRIPTION
**Pull request by Crashillo**
## :v: What does this PR do?
**This PR is just an HYPOTHESIS** to test the behaviour of the following rollbar errors:
- https://rollbar.com/Populate/gobierto/items/1460/
- https://rollbar.com/Populate/gobierto/items/1459/
- https://rollbar.com/Populate/gobierto/items/1527/
- Perhaps this also: https://rollbar.com/Populate/gobierto/items/2705/

Looking the rollbar error times, they are triggered at startup. That's quite odd and difficult to replay, as the missing variables are defined in the `window` scope, so this hypothesis tries to delay when these variables are called, moving the script beneath the footer.

### CODE REVIEW

**Comment by ferblape** [comment]
OK, it looks like doesn't break anything. Worth to try.

**Comment by ferblape** [comment]
OK, I'm going to merge this. You can mark the Rollbars as Resolved and let's see if they happen again.

**Comment by amiedes** [comment]
Won't moving the JS out of the head cause issues with Turbolinks?

**Comment by ferblape** [comment]
We tested it in staging, and because it's just variable initialization is not causing an issue.

**Pull request merged**
