### PR TITLE
Small participation issues

### PR DESCRIPTION
**Pull request by apradillap**
Connects to https://github.com/PopulateTools/issues/issues/93

### What does this PR do?
- [x] Llamar a la Agenda -> "Agenda Participación" (para evitar que alguien piense que es la Agenda de Alcobendas en general) http://participacion.gobify.net/participacion
- [x] Proceso: Enlace "Reuniones" en nav local, debe enlazar a la agenda del proceso http://participacion.gobify.net/participacion/p/pacto-social-mujer
- [x] Process: Information page: No formatting filter is being applied to the text. Apply it http://madrid.gobierto.dev/sandbox/participation_group_info http://participacion.gobify.net/participacion/p/presupuestos-participativos-alcobendas/informacion
- [x] Wrong order of items: http://participacion.gobify.net/participacion/noticias 
- [x] When going to participate in a Poll, locale not translated: user.census_verifications.messages.not_verified Test in http://participacion.gobify.net/participacion/p/presupuestos-participativos-alcobendas/encuestas "Poll de prueba"
- [x] Activity mail: "Anunciamos los Presupuestos Participativos de Alcobendas para el 2018: Página publicada" - Remove "Página publicada"; and link all the title instead
- [x] Add doc: slug field has wrong HTML input type (textarea instead of text) ie. http://participacion.gobify.net/admin/attachments/file_attachments/new?collection_id=77
- [x] Process Edit: Seleccionar por defecto en Tipo de grupo: Proceso http://participacion.gobify.net/admin/participation/processes/new
- [x] Process Edit: The switch draft|public is common for Process tab and the Information tab, I'd remove the switch in Information (if it's simple, otherwise let's wait until we iterate here with collections) http://participacion.gobify.net/admin/participation/processes/5/process_information/5/edit
- [x] Edit Poll: A token_preview is offered even if the Poll is marked as public. The token is displayed when: http://participacion.gobify.net/admin/participation/processes/12/polls
`
poll.draft? || !poll.open? || poll.process.draft?
`
@furilo Is this right?

- [x] Front: In an event, only the place is being shown, but not the address. Show the address and link it to Google (ie. http://participacion.gobify.net/participacion/procesos/presupuestos-participativos-alcobendas/agendas/2017-10-06-presentacion-de-los-presupuestos-participativos-2017 ) I haven't been able to reproduce the problem, you can pass me the url @furilo .

### Doubts/Already
- [x] Edit Pool: Locales not translated for Pool type. Already translated. http://participacion.gobify.net/admin/participation/processes/9/polls/new You can change the English language to Spanish and the type of survey if you do change the language change.

### New Issues
- Front: Process Home: Interest Info block: link scope (as Issue)

### CODE REVIEW

**Comment by amiedes** [comment]
@furilo about this:

captura de pantalla 2017-10-09 a las 16 42 58

I'm passing the preview token when the poll is published but still closed so an admin can preview how the questions look in the front. Otherwise he/she would be able to see the poll in the listing but not the questions inside.

**Comment by furilo** [comment]
@amiedes you are right. I was not taking into account if the poll was opened.

**Comment by apradillap** [comment]
I have added the links so that you can test each point, I have just tested them.

**Comment by furilo** [comment]
- [x] In the Home, Issues block with Agenda, Latest and News, we keep saying just "Agenda". Put "Agenda Participación". In the top right nav, leave Agenda

- [x] Process: Information page: No formatting filter is being applied to the text. Apply it http://madrid.gobierto.dev/sandbox/participation_group_info http://participacion.gobify.net/participacion/p/presupuestos-participativos-alcobendas/informacion ---- I'm not seeing this

**Review by amiedes — APPROVED** [review]

**Comment by apradillap** [comment]
@furilo I changed the the first task of your previous comment but I don't understand the second.

I attach two captures from sandbox and the same text in localhost/staging

sandbox
localhost

**Comment by apradillap** [comment]
With rich_text_area_tag, I solved Process: Information page: No formatting filter is being applied to the text. Apply it http://madrid.gobierto.dev/sandbox/participation_group_info http://participacion.gobify.net/participacion/p/presupuestos-participativos-alcobendas/informacion

**Pull request merged**
