### PR TITLE
Refactor lineas_tabla

### LINKED ISSUE #2646: JS when hovering on budget lines year
1. Go to budgets home
2. Scroll down to lines chart
3. Hover on a year
4. Data is not reloaded and two JS errors appear:

Screen Shot 2019-10-31 at 08 07 39

https://rollbar.com/Populate/gobierto/items/2808/
https://rollbar.com/Populate/gobierto/items/2807/

### PR DESCRIPTION
**Pull request by Crashillo**
fix https://rollbar.com/Populate/gobierto/items/2808/
fix https://rollbar.com/Populate/gobierto/items/2807/

Closes #2646 

## :v: What does this PR do?
Fix lineas_tabla chart user interaction

### CODE REVIEW

**Comment by ferblape** [comment]
Is it merged in staging? I still can see the JS error and the budget lines data keeps without data when I change the year.

**Comment by Crashillo** [comment]
It isn't ¬¬ wait 5 min, sorry

**Comment by Crashillo** [comment]
Go ahead

**Review by ferblape — APPROVED** [review]

**Comment by amiedes** [comment]
I'll merge this when I've done the tests

**Comment by entantoencuanto** [comment]
Is it ready to merge, @amiedes? Everything seems to be OK

**Pull request merged**
