### PR TITLE
New idea modal window

### PR DESCRIPTION
**Pull request by apradillap**
Connects to #921 

### What does this PR do?
- You can create ideas.
- If you are not logged in, it shows you a link for you to log in or sign in.
- If you don't enter either title or description, you will see the validation error
- Create idea test
- Create idea error test

### How should this be manually tested?
From a pool you have the button to create an idea.

### Pending
- I'm missing a design detail that I haven't just seen. The "new idea modal" is displaced to the left

### CODE REVIEW

**Comment by furilo** [comment]
- It seems we are not reflecting the type of pool that is configured. In the back you can choose betweeen Idea, Proposal, Question. We should reflect that in all places where we currently are only talking about "Idea". Some: 
  - [ ] The main button (if it's a Question pool type, it should read: "I've got a question!"
  - [ ] Filter: right now it always says "Mostrar ideas". It should say "Mostrar preguntas" etc
  - In the contribution modal window:
    - [ ] "Describe tu idea de forma" 
    - [ ] "¿QUIERES DAR DETALLES? DESARROLLA LOS PUNTOS PRINCIPALES DE TU IDEA|PREGUNTA|PROPUESTA" <- only show the corresponding one
- When creating a contribution: 
  - [ ] Title can't but description **can** be blank. Let's do like this: #960 
- Contribution created: 
  - [ ] We are not paragraphizing the description

**Comment by apradillap** [comment]
@furilo I have completed all the details you've told me and some more that I saw to distinguish the types of contributions. You can see them in staging

**Comment by ferblape** [comment]
I'm playing with the ideas and works great, just a couple of issues:

- could we translate the list of types of contributions?
- when the flash noticie is shown, could we include a link to the frontend?
- if you come to this page from a previous page, turbolinks breaks the calendar. Could you link to this page with turbolins disabled as have had to do in other pages such as new process?

**Comment by ferblape** [comment]
(My comment is about the admin pages to create/update a poll)

**Review by ferblape — APPROVED** [review]
👍 Code looks good to me

**Comment by apradillap** [comment]
👍 , @blat, first thing I put on tomorrow and we'll close it.

**Comment by apradillap** [comment]
@ferblape Ready in staging!!

**Pull request merged**
