### PR TITLE
Split test by modules

### PR DESCRIPTION
**Pull request by Crashillo**
## :v: What does this PR do?
Split circleci logic into different tests by modules

### CODE REVIEW

**Comment by ferblape** [comment]
@Crashillo @entantoencuanto review please, this is ready to me

**Comment by Crashillo** [comment]
Wow, only 4' to run admin tests 😯 wunderbar!

**Comment by Crashillo** [comment]
Three last times`tests_engines` are failing in the same tests. Perhaps r they actually broken?

**Review by Crashillo — COMMENTED** [review]
✅ I cannot aprove it 'cause I'm the creator. So... check!

**Pull request merged**
