### PR TITLE
Gobierto Data / Hide JSON and XLS options from the download menu

### PR DESCRIPTION
**Pull request by jorgeatgu**
Closes 

https://github.com/PopulateTools/gobierto/issues/3421

## :v: What does this PR do?

Hide JSON and XLS options from the download menu

## :mag: How should this be manually tested?

Staging

### CODE REVIEW

**Comment by ferblape** [comment]
Maybe it wasn't necessary that you updated anything, because when https://github.com/PopulateTools/gobierto/issues/3482 is implemented the formats will be read automatically from the API, right?

**Comment by jorgeatgu** [comment]
Yes, the list is automatically created with the API formats.

Now that we only have one format available, maybe it doesn't make much sense to show a list with only one item. This way, we save the user a click.

Screenshot 2020-11-26 at 08 06 12

**Comment by furilo** [comment]
We'll have more formats in the future, so leave it as it is. If this starts being used a lot we can reconsider your suggestion (which makes total sense)

**Comment by jorgeatgu** [comment]
OK.

**Comment by ferblape** [comment]
Hey, did you revert this changes in staging? To avoid conflicts in the future

**Comment by jorgeatgu** [comment]
> Hey, did you revert this changes in staging? To avoid conflicts in the future

Done!

**Pull request closed without merging**
