### PR TITLE
508 - Attachment for content block

### PR DESCRIPTION
**Pull request by furilo**
Connects to #508 

### What does this PR do?

Provides de UI controls to

- upload a file attached to a row from a content block
- show the corresponding download file control in the content block in the front (warning: I've hardcoded the control, it should be properly integrated)

### CODE REVIEW

**Comment by amiedes** [comment]
Don't merge, I just found some failing edge cases.

**Comment by amiedes** [comment]
Hey @ferblape, the backend of this issue is ready. I'm not fully convinced about the two-step initialization for FormObjects:

```ruby
@person_form = PersonForm.new(id: params[:id], admin_id: current_admin.id, site_id: current_site.id)
@person_form.assign_attributes(person_params)
```
because every controller that instantiates form objects that have content block records with attachments must be aware of this. What do you think about correcting this after we make the transition to the "Attachment model"?

**Comment by ferblape** [comment]
A few comments:

- [x] you need to add the validation of presence of site in the `PersonStatementForm`
- [x] When the content block record doesn't have an attachment don't show delete attachment checkbox
- [x] When a new attachment has been added, and the Save button clicked, show something in the content block record for the user to understand there's an attachment being uploaded
- [x] When a content block record is being edited and the attachment is marked to be removed, after the save button is clicked, remove the attachment from the content block record row
- [x] Remove the getter of `site_id`, so the user of the Form object is forced to set it in the initializer

And I agree with your comment, although I don't see an easy solution.

**Review by ferblape — APPROVED** [review]
+1

**Comment by ferblape** [comment]
@furilo, please, review in staging, specially the part of deleting an existing attachment from a content block record.

**Comment by furilo** [comment]
- [ ] Admin: There is a string (Attachment file) which is not getting translated: 
captura de pantalla 2017-06-02 a las 15 12 32

**Comment by furilo** [comment]
Ready to merge once the string issue is fixed.

**Comment by amiedes** [comment]
Done!

**Comment by amiedes** [comment]
Wait, I'll need to fix the unused translation keys

**Comment by ferblape** [comment]
I'll take care.

**Pull request merged**
