### PR TITLE
1267 gobierto auth strategies

### PR DESCRIPTION
**Pull request by entantoencuanto**
Related with #1267 

### What does this PR do?
Allows the use of alternative mechanisms for users authentication / authorization in site.

By default the site has the email/password mechanism, but from admin site administration there are different authentication modules which can be enabled. If one of them is enabled, the application uses an alternative session form or redirects to another site whose responsibility is the authorization of the user. The content of the alternative session form is provided by the auth strategy. The controller uses an object form provided by the auth strategy module, and it contains the logic to create a valid user session. The auth strategy files must be stored under vendor/auth_strategies/ An example of the structure of an strategy can be reviewed in vendor/auth_strategies/null_session/

### How should this be manually tested?
Enable "Null Session" from site admin configuration and try to make sign in ;)

### Does this PR changes any configuration file?

- [ ] new environment variable in `.env.example`?
- [x] new entry in `config/application.yml`?
These lines has been added to application:
```
  auth_modules:
    -
      name: null_strategy
      description: Null Strategy
      session_form: NullStrategySessionForm
      default: false
```
Further modules can be added there and they will be available in the admin site configuration form

- [ ] new entry in `config/secrets.yml`?

(Changes in these files might need to update the role in Ansible)

### CODE REVIEW

**Comment by entantoencuanto** [comment]
It appears that with the last commit the problems with staging environment eager loading are solved. Now the namespace associated with custom authentication is available and the Null Strategy works as expected.

**Comment by entantoencuanto** [comment]
Some changes has been added:
* For the links in application to actions only allowed to authenticated users which open via AJAX a login form, instead of make a redirect when the authentication strategy is defined outside, a message with a link to authentication provider is shown.
* After registration, the password fields can be disabled by the auth strategy on confirmation and settings forms. If none of the auth strategies enabled for a site include `password_enabled: true` in `application.yml` password fields won't be shown in forms and related validations won't be performed.

**Comment by ferblape** [comment]
@entantoencuanto we've just realized that the strategies are available in all the sites. For staging that's fine, but in production we should limit this, and the strategy should be only visible in the sites configured in the YAML file of the strategy. What do you think?

**Comment by entantoencuanto** [comment]
I can add an attribute to configuration with a white list of the sites a strategy is available

**Comment by entantoencuanto** [comment]
Added a configuration option in `application.yml` for auth strategies named `domains`:

* If not present or with nil value the strategy will be available for all sites.
* To restrict the availability of the auth strategy for a group of sites the value of this attribute must be an array containing their domains.

**Comment by ferblape** [comment]
Please, review this flash message:

screen shot 2018-01-16 at 11 55 38

**Comment by ferblape** [comment]
I also found a translation missing:

screen shot 2018-01-16 at 12 04 46

**Comment by entantoencuanto** [comment]
The missing translation issue has been included in #1343

**Pull request merged**
