### PR TITLE
[WIP] Groups and permissions

### LINKED ISSUE #2152: Groups and permissions
- [x] Front-end
- [ ] Implementation
  - [ ] TBD
  - [ ] ...

### PR DESCRIPTION
**Pull request by furilo**
Closes #2152

## :v: What does this PR do?

- [x] Provides front-end code for admin screens
- [ ] Implementation

## :shipit: Does this PR changes any configuration file?

- [ ] new environment variable in `.env.example`?
- [ ] new entry in `config/application.yml`?
- [ ] new entry in `config/secrets.yml`?

(Changes in these files might need to update the role in Ansible)

## :book: Does this PR require updating the documentation?

- [ ] new site configuration variable?
- [ ] new site template?
- [ ] new module/submodule settings?
- [ ] significant changes in some feature?

### CODE REVIEW

**Comment by furilo** [comment]
Please @ferblape @entantoencuanto review the screens I've updated/included. I think I'm not missing anything from what we talked: 

- New option in Admin/Users: Groups and permissions http://madrid.gobierto.test:3000/sandbox/admin_users_admins:

image

- List of groups http://madrid.gobierto.test:3000/sandbox/admin_users_groups: 

image

- Group configuration http://madrid.gobierto.test:3000/sandbox/admin_users_groups_group: 

image

**Comment by ferblape** [comment]
Missing things, that we can solve ourselves and it's not necessary to add them to the sandbox:

- in the list of groups, add an "New" button to create a new group
- form to create a new group / update the group name: it can be a modal asking for the name of the group (localized?) and redirecting to the edit form
- in the user form, add a dropdown to select the admin role, right?

**Comment by entantoencuanto** [comment]
The "Ver usuario" link is a link to manage admins belonging to the group or it has another purpose?

**Comment by furilo** [comment]
> The "Ver usuario" link is a link to manage admins belonging to the group or it has another purpose?

Doesn't apply. It's the standard component for that box in the sandbox. I've updated it, along with issues @ferblape outlined.

**Comment by ferblape** [comment]
So can I merge this one?

**Pull request closed without merging**
