### PR TITLE
Integrate Gobierto People module in User namespace

### PR DESCRIPTION
**Pull request by danguita**
Connects to #223.

### Review notes

In this PR we're for now bootstrapping the Gobierto People module within User namespace. It is here just to open the discussion on how these new features should be implemented. Please, do not merge it for the time being.

### What does this PR do?

Here's what we have done so far:

#### Module's homepage

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/

- People summary
  - People filtering (categories, parties and political groups) links.
  - View all link.
- Events summary
  - Past events link.
  - View all link.
- Posts summary
  - View all link.
- Other sections links:
  - "Salarios y retribuciones" links to Statements view.
  - "Obsequios y regalos" links to an environment-level defined URL (`$PEOPLE_GIFTS_SERVICE_URL`).
  - "Viajes y desplazamientos" links to an environment-level defined URL (`$PEOPLE_TRAVELS_SERVICE_URL`).

#### People section

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos

- People grid view.
- People filtering options:
  - By Government party: http://madrid.gobierto.dev/cargos-y-agendas/cargos (that's the default filter).
  - By Opposition party: http://madrid.gobierto.dev/cargos-y-agendas/cargos-en-oposicion.
  - By Executives category: http://madrid.gobierto.dev/cargos-y-agendas/cargos-directivos.
  - View all, reset filters: http://madrid.gobierto.dev/cargos-y-agendas/todos-los-cargos.
  - By political groups (those are managed in the Admin UI). e.g.: http://madrid.gobierto.dev/cargos-y-agendas/grupos-politicos/742272447/cargos.
- Subscription module.

#### Events section

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/agendas/eventos

- Events list view.
- Events filtering options:
  - By Government party: http://madrid.gobierto.dev/cargos-y-agendas/agendas/eventos (that's the default filter).
  - By Opposition party: http://madrid.gobierto.dev/cargos-y-agendas/cargos-en-oposicion/agendas/eventos.
  - By Executives category: http://madrid.gobierto.dev/cargos-y-agendas/cargos-directivos/agendas/eventos.
  - View all, reset filters: http://madrid.gobierto.dev/cargos-y-agendas/todos-los-cargos/agendas/eventos.
  - By political groups (those are managed in the Admin UI). e.g.: http://madrid.gobierto.dev/cargos-y-agendas/grupos-politicos/742272447/agendas/eventos.
  - Every filtering endpoint has in turn two separate views:
    - Upcoming events: http://madrid.gobierto.dev/cargos-y-agendas/agendas/eventos (that's the default view).
    - Past events: http://madrid.gobierto.dev/cargos-y-agendas/agendas/eventos-pasados.
- Calendar component:
  - Displays a calendar in which days with events are highlighted (they are rendering a link, actually).
  - Provides a single day view to retrieve all Events that match the current filters within that day. e.g.: http://madrid.gobierto.dev/cargos-y-agendas/agendas/eventos?date=2017-02-17.
- Person's agenda selector (a.k.a. agenda switcher control).
- Subscription module.

#### Posts/Blog section

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/blog/posts:

- Posts excerpts view. Each post summary has the following format:
  - Title (links to the Post's single view).
  - Author (links to the Author's blog feed).
  - Publishing date.
  - Tags (each of them link to the corresponding Tag filtered view).
  - Body excerpt.
  - "Continue reading" link.
- Subscription module.

#### Statements section

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/bienes-y-actividades

- Statements list view.
  - Each statement list item has a reference to its Owner.
  - Subscription block.

---

#### Person Profile view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536

- Sidebar, Large avatar image.
- Sidebar, dynamically built contact methods (they come from a specific Content Block titled "Contact methods", which data are being presented through `GobiertoPeople::PersonDecorator`).
- Upcoming Events block.
- Recent activity block.
- Subscription block.

This is the structure required to store contact methods:

| service_name  | service_handle | service_url | service_notes (optional) |
| --- | --- | --- | --- |
| Twitter | @richard | https://twitter.com/richard | Richard's Twitter account |

A `ContentBlockRecord` representing these data would look like this:

```ruby
{ "service_name" => "Twitter", "service_handle" => "@richard", "service_url" => "https://twitter.com/richard", "service_notes" => "Richard's Twitter account" }
```

#### Person Biography view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/biografia

- Link to Attached file URL.
- Content Blocks table view.

#### Person Events view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/agenda/eventos

- As in the generic Events view (http://madrid.gobierto.dev/cargos-y-agendas/agendas/eventos), display a scoped Events list view.
- Allow filtering by Upcoming or Past events.
- Subscription block.

#### Person single Event view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/agenda/eventos/212452004.

- Event date and title.
- Event Attendees.
  - Link to Person's profile when the Attendee comes from our database.
- Event Locations.
  - Link to Google Maps Places URL.
- Subscription block.

#### Person Blog/Posts view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/blog/posts

- Post excerpts list, skipping the Author's name because or redundancy.
- Links to Tag filtered view.

#### Person single Post view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/blog/posts/585972795

- This view is very similar to the Post excerpt view, showing the full Post body and keeping the original formatting.
- Subscription block.

#### Person Statements view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/bienes-y-actividades/

- This URL automatically redirects to the latest available Statement. 

#### Person single Statement view

Entry point: http://madrid.gobierto.dev/cargos-y-agendas/cargos/933465536/bienes-y-actividades/689271360

- Link to the Attached file URL.
- Block to reference to other available Statements, and allow switching between them.
- Content Blocks table view.
- Subscription block.

---

#### User Subscriptions

- The User Subscriptions feature has been enabled in the following models, and here are the attributes we are looking for changes on:
  - `GobiertoPeople::Person`
    - `name`
    - `charge`
    - `bio`
    - `visibility_level`
  - `GobiertoPeople::PersonEvent`
    - `title`
    - `starts_at`
    - `ends_at`
  - `GobiertoPeople::PersonPost`
    - `title`
    - `body`
    - `visibility_level`
  - `GobiertoPeople::PersonStatement`
    - `title`
    - `published_on`
    - `visibility_level`

Please note that generic events such as just "created" are automatically being notified as well.

---

#### Other enhancements

- The User Subscriptions feature has been enhanced by allowing toggling any available subscription through a single endpoint.
  - The User subscriptions view (http://madrid.gobierto.dev/user/subscriptions) has also been updated to allow rendering more complex resources' references (such any of the Person-dependent resources, which requires a `person_id` param to retrieve the routed path).
- We have implemented a first approach for Person event moderation through the Admin UI. It is quite simple but enough to leave nothing behind until we move forward in the roadmap.

#### What's missing?

- Person Activity feed. It would be needed to attach all noticeable Person-related events to be able to render the Person Activity feed. An improvement could be to do so at FormObject level instead of Controller level, as we do in the User Subscription feature through the Trackable extension. We are now building an empty array of Activities just to have a placeholder to work with.
- ~~PersonEvent moderation actions. Right now all Events that come from the Admin UI are being published automatically, so the "moderation pending" filtered view isn't being used actually. The idea in future implementations is to retrieve events from external services, which won't be published automatically.~~

#### Further improvements

- Set up fragment caching for certain HTML partials that are performing recurrent and potentially expensive queries to database.
- Find ways to speed up the test suite, specially the integration tests with JS driver.

--- 

### How should this be manually tested?

As a follow-up of the "What does this PR do?" block, let's continue checking all these features step by step, placing feedback in the corresponding sections:

- [x] 1. Module's homepage
- [x] 2. People section
- [x] 3. Posts/Blog section
- [x] 4. Statements section
- [x] 5. Person Profile view
- [x] 6. Person Biography view
- [x] 7. Person Events view
- [x] 8. Person single Event view
- [x] 9. Person Blog/Posts view
- [x] 10. Person single Post view
- [x] 11. Person Statements view
- [x] 12. Person single Statement view
- [x] 13. User Subscriptions
- [x] 14. Other enhancements

### CODE REVIEW

**Comment by danguita** [comment]
Yo @ferblape, I would say we reached a good point to push this one forward 🎉

Since this was getting huge, I tried to write a thorough description so that we can check and follow every single feature here. Anyways, let's check it out together when you have some time. I'm removing the **wip** label in the meantime.

**Comment by danguita** [comment]
@ferblape As discussed, we have implemented a first approach for Person event moderation through the Admin UI right in this branch. It is quite simple but enough to leave nothing behind us until we move forward in the roadmap. I've just updated the PR's description to reflect those changes 📝

**Review by ferblape — APPROVED** [review]
Approving this 🐘 PR

**Comment by danguita** [comment]
Thanks, mate! 🙌

**Pull request merged**
