### PR TITLE
635 Gobierto People URLs

### PR DESCRIPTION
**Pull request by amiedes**
Connects to #635 

### What does this PR do?

* Reorganizes Gobierto People URLs
* Adds slugs for `Person`, `PersonEvent`, `PersonStatement`, `PersonPost` and `PoliticalGroup`
* Adds `site_id` for `PersonEvent`, `PersonStatement` and `PersonPost`

### How should this be manually tested?

Slugs should work!

### Does this PR changes any configuration file?

No

### CODE REVIEW

**Comment by amiedes** [comment]
Do NOT merge yet

**Review by ferblape — CHANGES_REQUESTED** [review]
Code looks good to me. Congratulations because it wasn't a small one.

Just a small details, these links are broken:

screen shot 2017-05-18 at 14 51 35

**Comment by amiedes** [comment]
Done! 🎉 

Changes are squashed in the last commit.

**Review by ferblape — APPROVED** [review]

**Comment by furilo** [comment]
Hey, it seems you have prepended "cargos-y-agendas" to all URLs. But the idea was to get rid of that too, right? https://docs.google.com/spreadsheets/d/1TA2-fVTFzwcwjjdrMrzsuSBSgojrHsAV65zxKfnTTEE/edit#gid=0

**Pull request merged**
