### PR TITLE
2152 groups and permissions admin

### PR DESCRIPTION
**Pull request by entantoencuanto**
Related with #2152

## :v: What does this PR do?
* Replaces the admins permissions system with admin groups:
  * The admin groups are defined at site level and contains all permissions defined for admins
  * A regular admin with permissions for a site can be in one or more groups of the site
  * An admin is authorized to perform an action or manage a resource if belongs to at least one group with the associated permission enabled.
* The administration of gobierto_people calendar configuration, statements or person attributes is more restrictive with this PR. It's required not only permission for the module, but also permission for the specific person or all_people permission.
* The admins permissions management in administration panel is removed
* Activities are generated on creation and edition of a group and its permissions.
* How the admins are assigned to groups in admin is pending to be defined, maybe checkboxes with the groups available groups depending on the sites on which the admin has permission?

### Before this PR
2152_before
Screen Shot 2019-03-18 at 21 16 53

### After this PR
2152_after
Screen Shot 2019-03-18 at 21 17 06

## :shipit: Does this PR changes any configuration file?

No

(Changes in these files might need to update the role in Ansible)

## :book: Does this PR require updating the documentation?

- [ ] new site configuration variable?
- [ ] new site template?
- [ ] new module/submodule settings?
- [x] significant changes in some feature?

### CODE REVIEW

**Comment by ferblape** [comment]
@entantoencuanto I can't make it work.

I'm in http://burjassot.gobify.net/admin, I've just created a new admin group with some permissions: http://burjassot.gobify.net/admin/admin_groups/2/edit

- If I edit that admin group I can't see how to add people on it or how to update the permissions
- If I go to a regular admin from Burjassot, i.e. http://burjassot.gobify.net/admin/admins/5/edit I can't see how add it to the new group.

**Comment by entantoencuanto** [comment]
I'll add a basic form to edit association between admins and groups

**Comment by ferblape** [comment]
Yes, please, I can't see this form:

http://burjassot.gobify.net/sandbox/admin_users_user

Nor this:

http://burjassot.gobify.net/sandbox/admin_users_groups_group

**Comment by ferblape** [comment]
Maybe this Rollbar is related with the fact I can't edit the group, because the code is there: https://rollbar.com/Populate/gobierto/items/1427/

**Comment by ferblape** [comment]
Now it works very well, even when a user is assigned to multiple groups.

I'll merge this tomorrow morning

**Comment by furilo** [comment]
- [ ] Can't deassign a group for a user. Steps to reproduce:
  - In Staging-Espluges, I created a a Group (with permission for Plans), created a new user (alvaro.esplugues.pam@furilo.com) regular admin, and assigned the group. 
  - When trying to deassign a group, you save changes but the group is still marked for the user. Happens with one or various groups created.

Once this is fixed let's review again.

**Comment by ferblape** [comment]
Tested, I can deassign and reassign groups to an admin.

**Comment by furilo** [comment]
It works great!

**Comment by entantoencuanto** [comment]
I've fixed a bug, in some cases permissions for an admin in a site could be merged with permissions from groups on other sites to which the admin belongs

**Pull request merged**
