### PR TITLE
Gobierto Data / Add the selected locale to the API request

### PR DESCRIPTION
**Pull request by jorgeatgu**
Closes #N

## :v: What does this PR do?
- Add the selected locale to the API request to shown the translations of the descriptions.

### CODE REVIEW

**Comment by jorgeatgu** [comment]
It works well in local but not in staging.

If you change the language, it does not change the language description. The request is made with the locale, but the response does not change the description, it always shows the description in the same language. 

@ferblape @entantoencuanto any ideas?

[example locale=ca and description=es](https://mataro.gobify.net/datos?locale=ca) 
[example locale=es and description=ca](https://mataro.gobify.net/datos/costes-20200928/resumen?locale=es)

**Comment by ferblape** [comment]
I suspect it's an issue in the Vue side, if you check carefully the requests done when the page is load, the request `/api/v1/data/datasets/meta?stats=true` loads the names and the descriptions of all the datasets in all the locales, so Vue already has the info in any locale.

Any further request doesn't include the description of the dataset.

**Comment by ferblape** [comment]
@jorgeatgu this PR is necessary after Edu changes?

**Comment by jorgeatgu** [comment]
> @jorgeatgu this PR is necessary after Edu changes?

Yes. I'll re-run the tests and merged.

**Review by ferblape — APPROVED** [review]

**Pull request merged**
