### PR TITLE
387 - Upgrade people page

### PR DESCRIPTION
**Pull request by amiedes**
Closes [#387](https://github.com/PopulateTools/issues/issues/387), #[393](https://github.com/PopulateTools/issues/issues/393) and [#391](https://github.com/PopulateTools/issues/issues/391)

## :v: What does this PR do?

Modifies the current people page to display a sidebar with all the departments (only if they exist) and people filters per-department. Also makes the date filter available if it is configured.

## :mag: How should this be manually tested?

Pages which don't have departments available should maintain the previous behavior: http://esplugues.gobify.net/personas

The custom engine page should have the filters available: http://g*****.gobify.net/personas 

Youn can go to a department people page: http://g*****.gobify.net/personas/departamentos/departament-de-cultura
## :shipit: Does this PR changes any configuration file?

No

### CODE REVIEW

**Review by ferblape — APPROVED** [review]
👏

**Comment by ferblape** [comment]
Hmmmm, one thing left: sidebar links to departments should have a `start_date` / `end_date` parameter if the current page has a filter applied.

**Comment by amiedes** [comment]
@ferblape this is fixed:

> Hmmmm, one thing left: sidebar links to departments should have a start_date / end_date parameter if the current page has a filter applied.

You can test it here: http://g*****.gobify.net/personas?start_date=2018-05-29

**Comment by Crashillo** [comment]
I've moved the `yield` stuff to somewhere else to adapt people-gencat-layout

**Comment by ferblape** [comment]
Why there's no datepicker in this page?

**Pull request merged**
