### PR TITLE
Dynamic content UI component review and refactor

### PR DESCRIPTION
**Pull request by danguita**
Connects to #237.
Connects to #239.
Connects to #241.

### What does this PR do?

This PR brings together several improvements regarding the Dynamic content UI component. We also take advantage of the review to make some adjustments in terms of performance and maintainability.

### How should this be manually tested?

- [x] When adding a new row, set focus on the first input (#237).
- [x] Related to the point above, set focus on the first input when editing a row (extra 🎱)
- [x] Right after committing a record, display a new empty row (#239).
- [x] Currency fields are being formatted as you type via the Cleave.js library, and they have the right grouping and decimal marks for EUR currency (#241).

### CODE REVIEW

**Review by ferblape — COMMENTED** [review]
Instead of having static values for numbers format, I have changed this to read the settings from I18n.

**Comment by ferblape** [comment]
Taking care of the tests...

**Comment by danguita** [comment]
👌 Let me know if I can help with anything.

**Comment by ferblape** [comment]
Cleave is not playing well with commas, so I have changed slightly the tests. 

Anyway, I'm not sure now if this is the best solution, and maybe it's my fault for changing my mind here, but I think that the number fields should be stored as strings but without any format (just the decimal string) and we should format the output dynamically.

This is because I'm thinking when we export the data as CSV and the numbers must look as numbers, not as strings with the thousands separator.

So I'll accept this PR and I'll keep #241 open.

**Comment by ferblape** [comment]
I think Circle is not working with my push --force, because those tests are green in my laptop. I'm going to merge.

**Comment by danguita** [comment]
Yeah, it's hard to say what would fit better here in the future. Anyways, since we are not storing numeric fields at the moment, it is not trivial to perform calculations. I was thinking of keeping a "front" field in which we can do any kind of cool formatting, and an well-typed one for internal use only. I agree on pushing this one forward and taking care later 👍

**Comment by danguita** [comment]
Oh, I force pushes very often and CI builds are almost always triggered 😕 Let's see how it goes in `stable`.

**Comment by danguita** [comment]
Forgot to thank you for checking!

**Comment by ferblape** [comment]
Hmmm, I'll fix it, definitely is broken :D 

Thing is that I need to run `rake assets:precompile` to compile the assets for the tests each time.

**Comment by danguita** [comment]
Uhm, not happening here... The test runner is dealing with all the stuff for me:

```
$ bundle exec rails test test/integration/gobierto_admin/gobierto_people/person_statement_create_test.rb
```

**Comment by danguita** [comment]
Yay! 😜

**Pull request merged**
