### PR TITLE
Taxes receipt

### PR DESCRIPTION
**Pull request by martgnz**
### What does this PR do?
This PR implements the taxes receipt page in Sandbox (related with #740). I followed the provided screen closely, but I made some changes in the detail block to improve the readability.

You can check it here: http://madrid.gobierto.dev/sandbox/taxes_receipt.html

### Reference
https://projects.invisionapp.com/d/main#/console/10432841/221632401/preview

### CODE REVIEW

**Comment by furilo** [comment]
Great! Some things: 

- [x] Let's define an initial state: Selects should have an initial option like "Elige..."; quantities should be at 0 (don't bother changing it here), but for the total maybe we should add a slight call to action? Like "Define tus inmuebles y vehículos para calcular" in small type, to not break the current space?
- [x] Quantity boxes should have the same height as selects, to create continuity:
captura de pantalla 2017-07-27 a las 8 26 53

- [ ] As we don't have a submit button, once you select all options, I would scrollTo this position: 
captura de pantalla 2017-07-27 a las 8 30 37 

- [x] This "+" are a little bit misaligned?
captura de pantalla 2017-07-27 a las 8 27 35

**Comment by martgnz** [comment]
It seems that Safari is doing funny stuff again with Flexbox. Feedback noted 👍

**Comment by furilo** [comment]
@Crashillo tell me when you are ready for this and I'll explain it ;)

**Comment by ferblape** [comment]
Implemented and released to staging. You can check it in  http://esplugues.gobify.net/presupuestos/recibo

Two small details:

- [ ] position in the menu
- [ ] text to share in Twitter and FB? the heading text?

**Comment by furilo** [comment]
- Menu: "Recibo de tus impuestos", last option as it is currently
- Share message: "Comprueba cual es tu aportación al presupuesto de MUNICIPIO URL via @gobierto"

**Pull request merged**
