### PR TITLE
New top menu

### PR DESCRIPTION
**Pull request by furilo**
Connects to #131.

### What does this PR do?

It provides the HTML & CSS for the new top menu and interaction. Pending: integrate it in non-sandbox views, make the module listing dynamic.

@ferblape who can integrate this?

### CODE REVIEW

**Comment by danguita** [comment]
Hey, I think I can handle this. Just let me know if it's ready to be reviewed and integrated.

**Comment by furilo** [comment]
I'm just working on a few more things related to this, so wait a little while.

**Comment by danguita** [comment]
👌

**Comment by furilo** [comment]
OK David lets go. We are doing several things here: 

**Top links bar**
- On the top bar left we are only leaving the @site.configuration.links. 
- On the right side, we show the "Your account" dropdown. Here we'll show the same links as in the admin menu. 
- Also, the language selector. We'll list all available languages here for the time being. 

**Main nav menu**
- All the options of module navigation. Each section does not correspond with one module. We may have things from different modules in the same section. Do the most basic think you can think of because we may adjust things here.

@ferblape any other comment?

I have done all this in app/views/layouts/sandbox/application.html.erb which I think you have changed in one of your last PRs.

**Comment by ferblape** [comment]
Just one thing: we have English as an available language, and I'd remove it. I'd leave just ES and CA.

In the future, we can iterate this and allow a site to define a list of available locales and a default locale.

**Comment by danguita** [comment]
I'm integrating these changes right in this PR, please don't merge it until further notice 🙏

**Comment by danguita** [comment]
I've just created an Issue to take control over these changes: https://github.com/PopulateTools/gobierto-dev/issues/131.

**Comment by danguita** [comment]
We've ended up implementing new UI modules and refactoring a couple of things to keep everything clean and organized for the long haul. Here's a summary of those changes:

- Integrate the new markup.
- Implement Breadcrumb control.
- Implement Locale selection control and back-end.
- Implement Top menu control.
- Refactor Gobierto modules integration in terms of layouts and partials.
- Add some missing translations.

Having said that, this PR is getting huge and it may be blocking any coming changes so I'm about to merge and close it by myself. Anyway, it'd be great to have some post-merge feedback from you guys /cc @ferblape @furilo

**Pull request merged**
