### PR TITLE
Gobierto Data / Summary data

### PR DESCRIPTION
**Pull request by jorgeatgu**
Closes https://github.com/PopulateTools/issues/issues/1758

## :v: What does this PR do?

- Add the number of rows in a dataset to the metadata block.
- Place the metadata block in the main column, below the description.

## :mag: How should this be manually tested?

[Staging](https://esplugues.gobify.net/datos/poblacion-edad-sexo?sql=SELECT%2520%2a%2520FROM%2520poblacion_edad_sexo)

### Before this PR
before-rows

### After this PR
after-rows

### CODE REVIEW

**Comment by ferblape** [comment]
We are having some big datasets [example](https://demo-datos.gobify.net/datos/poblacion-edad-sexo/resumen) could you add a thousands separator if number of rows is less than 1M?

And if greater, could you round to 1M, 1.2M, and so on?

**Comment by furilo** [comment]
@jorgeatgu review the design: 

- icons and label have changed size
- put a gray separator under the description, if description is present, and add a margin-bottom
- put a gray separator under the metadata, and add a margin-bottom
- why "Previsualizar" and "Descargar" have different styles?

**Comment by jorgeatgu** [comment]
> We are having some big datasets [example](https://demo-datos.gobify.net/datos/poblacion-edad-sexo/resumen) could you add a thousands separator if number of rows is less than 1M?
> 
> And if greater, could you round to 1M, 1.2M, and so on?

If the number is equal to or greater than [1.000.000 round to 1M](https://demo-datos.gobify.net/datos/poblacion-edad-sexo/resumen?sql=SELECT%2520%2a%2520FROM%2520poblacion_edad_sexo%2520LIMIT%252050). In the other case, [the separator is added based on the locale.](https://demo-datos.gobify.net/datos/afiliados-seguridad-social?sql=SELECT%2520%2a%2520FROM%2520afiliados_seguridad_social)

**Comment by jorgeatgu** [comment]
> @jorgeatgu review the design:
> 
> * icons and label have changed size
> * put a gray separator under the description, if description is present, and add a margin-bottom
> * put a gray separator under the metadata, and add a margin-bottom
> * why "Previsualizar" and "Descargar" have different styles?

Done!

[staging](https://esplugues.gobify.net/datos/poblacion-edad-sexo?sql=SELECT%2520%2a%2520FROM%2520poblacion_edad_sexo)
Screenshot 2022-12-02 at 11 37 36

**Review by ferblape — APPROVED** [review]

**Review by furilo — APPROVED** [review]

**Pull request merged**
