### PR TITLE
Visualizations performance

### PR DESCRIPTION
**Pull request by Crashillo**
Closes https://github.com/PopulateTools/issues/issues/1276

## :v: What does this PR do?
- Hide the spinner when the vue application is actual mounted
- Mount in the DOM only for the current route path

### CODE REVIEW

**Comment by ferblape** [comment]
I don't fully understand how has it improved, but it loads much faster now

**Comment by Crashillo** [comment]
Wait there, there's a bug https://santfeliu.gobify.net/visualizaciones/contratos. The spinner doesn't hide.

> I don't fully understand how has it improved, but it loads much faster now

https://github.com/PopulateTools/gobierto/blob/5afe580baacf4cc07f0e063812f2c864eea73817/app/javascript/gobierto_visualizations/webapp/containers/subsidies/Home.vue#L15-L17

It's about the `v-if` directive. `v-show` simply applies a `display:none` to the markup, but all stuff is in the DOM. There's no reason to render a component if the user is not at such page. Those components are acting like a router, actually.

**Comment by ferblape** [comment]
> Wait there, there's a bug https://santfeliu.gobify.net/visualizaciones/contratos. The spinner doesn't hide.

It's working fine to me, what do you mean?

**Comment by Crashillo** [comment]
imagen

Don't you see this?

**Comment by Crashillo** [comment]
I figured out the problem. I fixed in subsidies, but I didn't in costs & contracts.

❤️ Lovely repeated code.

**Pull request merged**
