### PR TITLE
1167 Images in polls 

### LINKED ISSUE #1167: Allow images as options in polls
* An admin can upload an image associated with an answer
* A user can view the image, click to view it bigger in a lightbox, and vote the corresponding option

---- 

- [x] Design
- [ ] Implementation

### PR DESCRIPTION
**Pull request by furilo**
Closes #1167 

### What does this PR do?

Provides markup for images in polls. Integration pending.

### CODE REVIEW

**Comment by amiedes** [comment]
This can be reviewed in staging.

* You can edit this process polls stage in the back: http://madrid.gobify.net/admin/participation/processes/51/polls/38/edit
* And see its polls in the front: http://madrid.gobify.net/participacion/p/proceso-imagenes-encuestas/encuestas

The backend needs a bit of styles adjustment, because when I merged the updated version of master there were a few differences and I couldn't solve them. In particular the position of the edit/paperclip/delete icons and the text of the answer should appear on top of the image instead of next to it.

I pass the video link via Slack.

**Comment by ferblape** [comment]
Code is ok.

**Comment by amiedes** [comment]
Conflicts and tests are fixed

**Comment by ferblape** [comment]
We need to merge this to solve an issue with the translations js file. I'll keep the issue open until reviewed.

**Pull request merged**
