### PR TITLE
346 & 348 - Integrate agendas home and Department#show

### PR DESCRIPTION
**Pull request by amiedes**
Closes [#346](https://github.com/PopulateTools/issues/issues/346) and [#348](https://github.com/PopulateTools/issues/issues/348)

## :mag: How should this be manually tested?

Home:

http://gencat.gobify.net/cargos-y-agendas

Department pages:

http://gencat.gobify.net/departamentos/departament-d-interior
http://gencat.gobify.net/departamentos/departament-de-la-presidencia

## :shipit: Does this PR changes any configuration file?

No

### CODE REVIEW

**Comment by ferblape** [comment]
@amiedes you can link "conduct code" to this URL: http://governacio.gencat.cat/ca/pgov_ambits_d_actuacio/pgov_funcio_publica/alts-carrecs-i-directius/codi-de-conducta-alts-carrecs-personal-directiu/

**Comment by ferblape** [comment]
@amiedes also, could you order the people in this API endpoint by position? http://gencat.gobify.net/gobierto_people/api/v1/people?include_history=true&amp;limit=14

**Comment by amiedes** [comment]
@ferblape this is ready. Maybe @Crashillo wants to make some style adjustments.

**Comment by ferblape** [comment]
@amiedes the translations is broken:

screen shot 2018-06-18 at 15 15 28

**Pull request merged**
