### PR TITLE
209 & 1349 - Permit CMS pages & news to have participation layout

### LINKED ISSUE #1349: Incorrect preview url for process CMS page when process is draft
If a CMS page gets created in a collection of pages belonging to a drafted process, the generated URL does not have the preview token so we get a 404.

### PR DESCRIPTION
**Pull request by amiedes**
Closes [#209](https://github.com/PopulateTools/issues/issues/209)
Closes #1349 

### What does this PR do?

* Splits controllers for `app/controllers/gobierto_participation/pages_controller.rb` and `app/controllers/gobierto_participation/news_controller.rb`, so now pages belonging to participation module can be routed to this controller and inherit the participation layout.
* Fixes the scope of a uniqueness validation in [app/models/gobierto_common/collection.rb](app/models/gobierto_common/collection.rb), `container_id` should be scope in site.
* Fixes the name of the `app/views/gobierto_cms/templates/_new.html.erb` partial. Should be `_news`. This was causing some exceptions.

### How should this be manually tested?

I've done the following testing, but feel free to test other flows:

* Created a collection of news for the Participation module ([http://newalcobendas.gobify.net/admin/collections/167](http://newalcobendas.gobify.net/admin/collections/167))
  * Created a news in this collection and check it has the right layout in the front ([http://newalcobendas.gobify.net/participacion/noticias/noticia-participacion](http://newalcobendas.gobify.net/participacion/noticias/noticia-participacion))
* Created a collection of pages for the Participation module ([http://newalcobendas.gobify.net/admin/collections/166](http://newalcobendas.gobify.net/admin/collections/166))
  * Created a page in this collection and check it has the right layout in the front ([http://newalcobendas.gobify.net/participacion/paginas/pagina-estatica-participacion](http://newalcobendas.gobify.net/participacion/paginas/pagina-estatica-participacion))

### Doubts

I have doubts about the collection of pages Alvaro mentions in the issue ([http://newalcobendas.gobify.net/paginas/acerca-de](http://newalcobendas.gobify.net/paginas/acerca-de)), since now it still has the normal layout. I understand the current behavior is the right one, since the collection is scoped on the site, not participation.

### Future work

I think there's a good opportunity for refactor in the methods in `app/models/gobierto_cms/page.rb` that retrieve pages from a colleciton, module, site etc. Since refactoring this spans to many other files, I've limited myself to adding a few clarifying comments before the methods.

### Does this PR changes any configuration file?

No

### CODE REVIEW

**Comment by furilo** [comment]
I've created a page collection inside a process, and get this error when trying to view the collection: 

NoMethodError in GobiertoAdmin::GobiertoParticipation::Processes::ProcessPagesController#index
undefined method `news_in_collection' for nil:NilClass

**Comment by amiedes** [comment]
I've done the following changes:

* When listing pages in the admin from *participation pages collection* or a *process pages collection*, use the default list view we're using for showing a collection of pages.
* When editing from the admin pages belonging to *participation pages collection* or a *process pages collection*, use the default edit view we're using for editing CMS pages instead of showing the breadcrumb used for editing news.
* When showing in the front a page belonging to a process, use the same controller and views used for news (`::GobiertoParticipation::Process::PagesController`), but hide the left column which is shown for news. ***1**

***1** As discused with @apradillap and @ferblape, given that making a separate controller for pages and news in this case implies lots of renaming, and that #932 will be implemented, we will temporarily access process pages under the `/noticias` URL.

**Comment by amiedes** [comment]
Closes also #1349. This is ready.

**Comment by ferblape** [comment]
@amiedes which is the difference between the page Alvaro created (http://newalcobendas.gobify.net/paginas/acerca-de) and yours  (http://newalcobendas.gobify.net/participacion/paginas/pagina-estatica-participacion) ??

They look different

**Pull request merged**
