### PR TITLE
Performance plugins

### PR DESCRIPTION
**Pull request by Crashillo**
### What does this PR do?
Includes two webpack plugins to measure performance: `BundleAnalyzerPlugin` ~and `SpeedMeasurePlugin`~. Both are enabled only for development environment.

_BundleAnalyzerPlugin_ was already there, but disabled. Now, it's always enabled at  _http://localhost:8888/_ once you run the application.

On the other side, `terser` plugin, only useful to circleci developments (it decreases a lot the hot-module-reloading) has been activated only for _test_ environment.

Besides, _webpacker_ configuration (`config/webpack`) has been simplified, separating some webpack modifications to its own files. It also allows to add libraries to different environments.

Development assets output has been reduced, through [stats webpack config](https://v4.webpack.js.org/configuration/stats/), set to `errors-warnings`.

### CODE REVIEW

**Comment by ferblape** [comment]
Hold on, all the tests are broken when use the headless browser https://app.circleci.com/pipelines/github/PopulateTools/gobierto/2649/workflows/48c0852c-f206-4c51-9ba6-4d5c84e47837/jobs/23593/parallel-runs/1?filterBy=FAILED

**Comment by ferblape** [comment]
It's weird, if I run `RAILS_ENV=test bin/rails assets:precompile` it totally blocks my computer

**Comment by ferblape** [comment]
@Crashillo I think you can merge master and this will be ready

**Comment by Crashillo** [comment]
All green.... a small tear drop slides down my cheek

**Comment by ferblape** [comment]
@Crashillo would be good to add this:

> BundleAnalyzerPlugin was already there, but disabled. Now, it's always enabled at http://localhost:8888/ once you run the application.

into readme.io. In frontend or maybe as a page in Environment setup? https://gobierto.readme.io/docs/environment-setup

**Comment by Crashillo** [comment]
I included it in https://gobierto.readme.io/docs/development-environment-1#appendix-4---webpack-configuration-files and also a reference to that link in https://gobierto.readme.io/docs/frontend-contributing#webpack-debugging-tools because I wasn't sure where fits better.

**Pull request merged**
