### PR TITLE
Liquidify plans page

### LINKED ISSUE #1519: Liquidify Plans page

### PR DESCRIPTION
**Pull request by apradillap**
Closes #1519 

## :v: What does this PR do?

Plan introduction and plan footer liquid is allowed,  or text or whatever you want.

## :mag: How should this be manually tested?

You can add for example:

`<p>{{ "gobierto_participation.welcome.index.improve_city_p1" | t }}</p>`

### After this PR

captura de pantalla 2018-03-20 a las 10 13 56

## :shipit: Does this PR changes any configuration file?

No

### CODE REVIEW

**Comment by furilo** [comment]
@ferblape can you merge this?

**Comment by ferblape** [comment]
Let me check, I'm not sure he finished with our feedback because he started with the issue of liquidify the layout.

**Comment by furilo** [comment]
I'd need some of the things he did, for my part we can close this and
continue on another one if there are things pending.

**Comment by ferblape** [comment]
OK!

**Pull request merged**
