### PR TITLE
Page and menu option to manage themes HTML

### PR DESCRIPTION
**Pull request by furilo**
Markup for #782

### CODE REVIEW

**Review by ferblape — CHANGES_REQUESTED** [review]
Code looks great, you have been able, without much information from side, to integrate the new model with all the hooks, events, and so on in Gobierto. Congrats! 👏 

You just forget one thing, which is the translation of the activities. Activities are listed in the admin home page when you log in:

screen shot 2017-07-14 at 08 05 06

And the new issues activities are not translated. Just add those translations and we'll be ready to release.

**Comment by furilo** [comment]
Hooray!!!

**Comment by apradillap** [comment]
I solved your comments and the breadcrumb that I saw with @ferblape yesterday. I have completed the documentation relation with adding a new module. I merged in staging 👍

**Review by ferblape — APPROVED** [review]
👍

**Pull request merged**
