### PR TITLE
Responsive plans

### PR DESCRIPTION
**Pull request by Crashillo**
Closes PopulateTools/issues#708

## :v: What does this PR do?
Mobile version of gobierto-plans

## :eyes: Screenshots

| View | Screenshot |
|------|------------|
| home | imagen     |
| node open | imagen     |
| project detail | imagen     |

### CODE REVIEW

**Review by ferblape — APPROVED** [review]
Good to me.

**Comment by furilo** [comment]
- [x] It doesn't make sense to show both headers, since they almost have the same content. Let's remove the second one. 
- [x] Reduce the padding of the main heading, so the height gets reduced
- [x] Project view: remove the second header
- [x] Project view: the padding of the main header and the project title should match
- [x] Project view: reduce the font-size of the project title so we create hierarchy between main header and project title

image

**Comment by Crashillo** [comment]
@furilo "second one / second header", you mean the breadcrumb, don't you?

**Comment by furilo** [comment]
> @furilo "second one / second header", you mean the breadcrumb, don't you?

Second header when in

image


Breadcrumb when in: 

image

**Comment by Crashillo** [comment]
Screenshots updated w/ the new changes. Deployed as well.

**Review by furilo — APPROVED** [review]

**Pull request merged**
