### PR TITLE
749-750 - CustomArea, custom BudgetLine name and descriptions

### PR DESCRIPTION
**Pull request by amiedes**
Connects to #749 and #750 

### What does this PR do?

* Adds `GobiertoBudgets::CustomArea`, which permits municipalities to have their own budgets classification.
* Adds support for customizing BudgetLine name and descriptions for each municipality. This is done through the `GobiertoBudgets::Category` model.

### Important notes

* For this functionality to work, staging and production PostgreSQL DBs must have custom categories inserted. ElasticSearch needs a new type (custom) and a new column (ine_code).

Related: [#48](https://github.com/PopulateTools/populate-data-indicators/issues/48) and [#49](https://github.com/PopulateTools/populate-data-indicators/issues/49)

### CODE REVIEW

**Comment by ferblape** [comment]
We need to amend the search to take into account the personalized results:

screen shot 2017-06-26 at 17 58 59

In this example I have overwritten a category but the search still returns the original one.  This happens in `GobiertoBudgets::SearchController`. I suggest to read all the categories of the site, and overwrite the results from the ES with that collection of results.

**Comment by ferblape** [comment]
Ah, and remember to deploy to staging each time you open a PR!

**Comment by ferblape** [comment]
Another issue I have found: in the tree, the first level uses the personalized category name, but the others can't use it.

screen shot 2017-06-27 at 08 33 18

If I visit those budgtet lines, I can see the personalized name.

**Comment by amiedes** [comment]
OK! 👷 🏗

**Pull request merged**
