### PR TITLE
Select homepage

### PR DESCRIPTION
**Pull request by apradillap**
Connects to #1046 

### What does this PR do?

An admin will be able to choose which module act as the global site homepage. The first task has been done because the functionality is in production and the section part for the front is not yet implemented (https://github.com/PopulateTools/gobierto/issues/927)

### How should this be manually tested?

Editing a site. I have followed the same casuistry as when selecting a default locale where if the selected locale is not among the allowed ones, it also adds it to the allowed, so, if a module is selected as homepage and it is not among the selected modules, it is also selected.

### Execute
This task selects in the order in which the homepages were selected to define the homepage.
`
rake data:migrate
`

### Does this PR changes any configuration file?

Fernando, in order to have controlled the modules that can be selected as root_paht I put it in the application.yml, next to where modules are added but we have to modify the application.yml in the servers with these values.

In application.yml:

```
  site_modules_with_root_path:
    -
      name: Gobierto Budgets
      namespace: GobiertoBudgets
    -
      name: Gobierto People
      namespace: GobiertoPeople
    -
      name: Gobierto Participation
      namespace: GobiertoParticipation
    -
      name: Gobierto Indicators
      namespace: GobiertoIndicators
```

### CODE REVIEW

**Comment by apradillap** [comment]
PendingTasks:
- [x]  Add root_path to pending modules
- [x]  Add documentation

**Comment by furilo** [comment]
I think we should control a little bit better the interactions between start page option and activated modules. Suggestions: 

- [x] Move the Start page select after the Activated modules
- [x] Control with JS that if I mark a module as activated or not, the corresponding option appears/disappears in the combo

**Comment by apradillap** [comment]
Pending to put in ansible the configuration of the application.yml, if not, in each deployment in staging the possibility of proving it is lost.

**Comment by furilo** [comment]
Good for me. I've included styles and html to fix #1051 (not 1050 as I referenced on the commit message)

**Comment by apradillap** [comment]
:wrench: ansible updated, executed and reviewed in production and staging.

**Review by ferblape — APPROVED** [review]
👍

**Pull request merged**
