### PR TITLE
Run linter autofixable issues

### PR DESCRIPTION
**Pull request by Crashillo**
## :v: What does this PR do?
This PR runs automatic fixes provided by each linting rule:

```
eslint --fix
stylelint --fix
```
Such default rules are extended via:
- eslint-plugin-vue
- stylelint-config-recommended
- stylelint-config-standard-scss

### CODE REVIEW

**Comment by ferblape** [comment]
@Crashillo could you check the conflicts?

**Comment by Crashillo** [comment]
Solved

**Comment by ferblape** [comment]
Hmmmm, there's a broken spec which is not broken in master, makes me suspect. Could you take a look? Ping me if you need help

**Comment by Crashillo** [comment]
Yep, I noticed before, I thought it would be related to the `master` conflicts. I see it's not. I'll take a look

**Comment by Crashillo** [comment]
I'm not being able to solve these tests: in my local environment they pass, so I presumed they were flaky tests... but any time I run them again in the server, they fail.

**Comment by ferblape** [comment]
Fixed by refreshing CircleCI cache

**Pull request merged**
