### PR TITLE
[WIP] Gobierto Plans

### LINKED ISSUE #1247: Gobierto Planification HTML
Marvel & Sketch shared

### PR DESCRIPTION
**Pull request by apradillap**
Closes #1247 
Closes [#251](https://github.com/PopulateTools/issues/issues/251)

### What does this PR do?

New module: Gobierto Plans

### How should this be manually tested?

Activate the module from admin and access to /planes

### Does this PR changes any configuration file?

- [x] new entry in `config/application.yml`?

### CODE REVIEW

**Comment by apradillap** [comment]
@Crashillo you can update the repository, run migrations and from /admin Customize site and check the new module **Gobierto Plans**, after this, you can go to /planes/strategic-plan, is preloaded in the database a plan with this json that's at the end.

I haven't changed the call to json in app/assets/javascripts/government_plans/app/controllers/plans_controller. js because the view is pending so still loaded with /sandbox/data/planification.json

```js
          getJson: function() {
            $.getJSON(window.location.href, function(json) {
                this.json = JSON.parse(json["plan_tree"]);
              }.bind(this));
            }
```

```json
[
  {
    "id": 760939060,
    "level": 0,
    "attributes": {
      "title": {
        "en": "City",
        "es": "Ciudad"
      },
      "colour": "#00FF00",
      "img": "http://santander.es/sites/default/themes/custom/ayuntamiento/img/logo-ayto-santander.png"
    },
    "children": [
      
    ]
  },
  {
    "id": 806940941,
    "level": 0,
    "attributes": {
      "title": {
        "en": "Economy",
        "es": "Economía"
      },
      "colour": "#FFFF00",
      "img": "http://santander.es/sites/default/themes/custom/ayuntamiento/img/logo-ayto-santander.png"
    },
    "children": [
      
    ]
  },
  {
    "id": 309767805,
    "level": 0,
    "attributes": {
      "title": {
        "en": "People and families",
        "es": "Personas y familias"
      },
      "colour": "#FF0000",
      "img": "http://santander.es/sites/default/themes/custom/ayuntamiento/img/logo-ayto-santander.png"
    },
    "children": [
      {
        "id": 953101899,
        "level": 1,
        "attributes": {
          "title": {
            "en": "Provide social assistance to individuals and families who need it for lack of resources",
            "es": "Proporcionar asistencia social a las personas y familias que la necesiten por falta de recursos"
          }
        },
        "children": [
          {
            "id": 1059973494,
            "level": 2,
            "attributes": {
              "title": {
                "es": "Necesidades básicas de las familias del Distrito Centro",
                "en": "Basic needs of District Center families"
              }
            },
            "children": [
              {
                "id": 812454004,
                "level": 3,
                "attributes": {
                  "title": {
                    "es": "Cubrir las necesidades básicas de las familias a las familias",
                    "en": "To cover the basic needs of families to families"
                  },
                  "progress": 50.25,
                  "starts_at": "2017-10-29",
                  "ends_at": "2018-04-29",
                  "status": {
                    "en": "In progress",
                    "es": "En progreso"
                  },
                  "options": {
                    "objetivos": "Improve pedestrian and vehicle safety",
                    "temporality": "annual"
                  }
                },
                "children": [
                  
                ]
              }
            ]
          }
        ]
      }
    ]
  }
]
```

**Comment by apradillap** [comment]
@Crashillo, I have added **uid** and **parent_id** fields to the json

**Comment by ferblape** [comment]
There are a few things pending in this PR to be merged in master:

- all the logic of generating the JSON should be extracted to a class, it could be a service object or a serializer, but we never have such complex logic in controllers
- once you extract the class, you should add unit tests to check the JSON generated
- once you have unit tests you should add acceptance tests navigating the tree and checking names, progresses, dates...
- with all these done you should refactor how the JSON is generated because you are doing many more queries than needed. In my laptop it takes 15 secs, and shouldn't take more than 1 sec

**Comment by apradillap** [comment]
I have made the changes requested by @ferblape  in the previous comment. In populate data I have added the translations of the optional keys of the projects. Missing part of the view (@Crashillo). Does Hugo do it in this PR? Or a new one?

captura de pantalla 2018-02-05 a las 17 32 26

I talked about it with Hugo:

- [ ] We show keys appear in configuration_data["option_keys"].
- [ ] In configuration_data["option_keys"] there are the translations

**Comment by ferblape** [comment]
Hmmmm, the unit tests you have added don't test anything. If you just check a method returns true it's like adding nothing.

Could you add tests to:

- Category#descendats
- Category#uid
- Category#children_progress
- a test PlanTree#call that checks the output

**Comment by apradillap** [comment]
- [x] Not displayed total %

**Comment by furilo** [comment]
- [x] When viewing this level we are listing Projects, not Actuations:

imagen

**Comment by apradillap** [comment]
I have been reviewing the PAM data to compare them with http://quadre.esplugues.cat/DadesObertes/Private/BIDocumentManager.aspx?BIRoleId=PAM&BIDocId=PublicPAM01 and we are showing more "projects" (projects + actions) than the client has because we also show the actions.

- [x] @Crashillo, a small detail that needs to be corrected is when you are at the level of actions, you should put projects (`configuration_data[level3]`) in the blue box. Thanks!

**Pull request merged**
