### PR TITLE
934 Participation admin screens

### PR DESCRIPTION
**Pull request by furilo**
Connects to #934 

### What does this PR do?

Provides the HTML for the first version of some participation admin screens we were lacking for participation, ready to implement: 

- [x] Home http://madrid.gobierto.dev/sandbox/admin_part
  The right column is just the public activity, in case is straitghforward to add it. If it poses any complication, we can leave for further iteration
- [ ] Poll results http://madrid.gobierto.dev/sandbox/admin_part_group_polls_poll_results
  The idea here is to do a first simple iteration, so we are flexible on the format of the table etc.
- [x] Both flashes present in http://madrid.gobierto.dev/sandbox/admin_part_group_polls_poll_edit, depending on the state. If the poll is closed, take directly to the results screen
- [x] Who can participate switch (all registered users, only verified users), both for Polls and Contributions - we will have this for any upcoming tool
  http://madrid.gobierto.dev/sandbox/admin_part_group_contributions_contribution_edit

All this can be implemented. If the who can participate switch is too much work, take it to another PR.

### CODE REVIEW

**Comment by amiedes** [comment]
I've created a *sub-issue* for the poll results points, and I'll be working on them [here (Poll results)](https://github.com/PopulateTools/gobierto/issues/1035)

**Comment by amiedes** [comment]
⚠️ I still have to make a little script to create seed data in staging for doing the acceptance before this PR is merged. I'll try to do it tomorrow so I don't block this. ⚠️

**Comment by amiedes** [comment]
I've done the seeding in staging. As a result the following poll results are available:

http://madrid.gobify.net/admin/participation/processes/17/polls/9/answers

[This](https://gist.github.com/amiedes/f08001198944c4bf733aca743f0cbec8) is the script I used. In case you have to run it again your probably can find it in `/tmp/seed-poll-answers.rb` and execute it with `rails runner`.

**Comment by ferblape** [comment]
The results part is quite broken, in 5 minutes I've got 3 rollbars:

- https://rollbar.com/Populate/gobierto/items/619/, when updating a poll
- https://rollbar.com/Populate/gobierto/items/619/ when updating a poll with answers. Could we capture this exception and don't show an error to the admin?
- https://rollbar.com/Populate/gobierto/items/617/ when trying to see the results of a poll with a single response. This is the URL of the poll: http://participacion.gobify.net/admin/participation/processes/9/polls/13/answers

Another issue. The method to check if a poll is open seems different in the public part and the admin part:

**public part** I can participate:

screen shot 2017-11-12 at 19 05 36

**admin part** poll is closed and I'm redirected to answers, but it raises an exception. If I introduce the [edit URL](http://participacion.gobify.net/admin/participation/processes/9/polls/13/edit) manually I see it's closed:

screen shot 2017-11-12 at 19 07 14

**Pull request merged**
