### PR TITLE
Allow select page/section as homepage

### PR DESCRIPTION
**Pull request by apradillap**
Closes https://github.com/PopulateTools/gobierto/issues/1150

### What does this PR do?

Add https://select2.org/dropdown to select page or section as the home page

### How should this be manually tested?

Edit stye

### Pending

- [x] Now the sections shown are from all sites, I have to add the scope
- [x] Display the new field name correctly

### Styles

- [x] Select does not display correctly when nothing is selected, it looks small

### CODE REVIEW

**Comment by ferblape** [comment]
Should we avoid to unpublish a page which is used as the homepage?

**Comment by apradillap** [comment]
It should be forbidden unpublish a page (homepage). I have doubts, how do we show it?

**Comment by ferblape** [comment]
@furilo now the home renders the page or the section without redirecting.

**Review by ferblape — APPROVED** [review]
👍

**Comment by ferblape** [comment]
Ok @apradillap let's show a flash message if the user tries to unpublish the page used as homepage.

**Review by ferblape — APPROVED** [review]
👍

**Pull request merged**
