### PR TITLE
68 - Fullcalendar view for GobiertoPeople person events index

### PR DESCRIPTION
**Pull request by amiedes**
Connects to [#68](https://github.com/PopulateTools/issues/issues/68)

### What does this PR do?

* Implements [Fullcalendar](http://fullcalendar.io) for gobierto people person agenda.
* Previous event listing is kept under the button *Lista*.
* *Past Events* filter under the *List* was causing some issues because past events weren't being retrieved using AJAX and page reloading was causing some Turbolinks issues.

  Turbolinks had to be disabled anyways afterwars, but since now we have the Fullcalendar view and the *Past Events* view does not make sense anymore, this filter has been hidden using a `<% pending do %>` block.  

image

### Does this PR changes any configuration file?

No

### CODE REVIEW

**Review by ferblape — APPROVED** [review]
👍 looks good to me!

**Comment by ferblape** [comment]
@furilo please review and confirm if it's fine to merge in master. You can test it here: http://santboi.gobify.net/agendas/francisco-gutierrez?locale=ca

Maybe I'd adjust the colors of the buttons when hovered:

screen shot 2017-10-01 at 08 48 11

**Comment by furilo** [comment]
I'm seeing one issue: If you go to the list view, and the go back to any of the other views, the events are not loading ok. If you browse again to any calendar views, it gets fixed. 

screencast 2017-10-02 09-55-32

**Comment by ferblape** [comment]
After investing a couple of hours trying to debug the error and trying different solutions to refresh the events heights once the container is shown again, it looks like there's no easy way to fix this. 

The solution we have come to is to use a min-height for events. Given that it's not hapening always, it's a good compromise.

**Pull request merged**
