### PR TITLE
2371 - Polish slickgrid interactions

### LINKED ISSUE #2371: Plans / Polish plugin select2 interactions
Avoid extra clicks by:

- [ ] When clicking on the select2 cell, automatically open the list (now you need 2 clicks)
- [ ] When you select an item form the select2, automatically close it and focus on the next cell to the right
- [ ] Don't show the cross to remove the current choice (does not make sense, since it's required)

### PR DESCRIPTION
**Pull request by amiedes**
Closes #2371

### CODE REVIEW

**Comment by furilo** [comment]
This is not in staging, right?

**Comment by amiedes** [comment]
> This is not in staging, right?

Not yet. I wanted to fix a couple of things more before merging.

**Review by ferblape — APPROVED** [review]
This works OK to me.

**Comment by ferblape** [comment]
Ping, what's pending here to merge?

**Comment by entantoencuanto** [comment]
> Ping, what's pending here to merge?

Everything works as described in the issue, except the focus on the next cell to the right after selecting an item on the select2, but I think that's OK.

**Comment by furilo** [comment]
can merge

**Pull request merged**
