### PR TITLE
Gobierto People module (first iteration)

### PR DESCRIPTION
**Pull request by danguita**
Connects to #190.

### Review notes

I'm not deploying this code to Staging since we're taking advantage of the PostgreSQL JSONB data type to store and query unstructured data, so we would need to upgrade our PostgreSQL instances to 9.4+ to release these changes.

Please note that we were using PostgreSQL 9.6.1 in development env (the latest release available at that time) until we decide the version to go in production. Let's take it into account to keep exactly the same version in every environment. i.e. production, staging, development and test.

---

### What does this PR do?

This PR introduces the new `gobierto-people` module and implements a first iteration in the Admin (`gobierto-admin`) namespace, mainly focused in back-end and architecture. It also implements a new component called `DynamicContent`, that The DynamicContent which allows managing schema free content blocks via a collection of helpers that significantly ease the integration process.

This component is key and will be extensively used in this new module, for now. Many other details on the implementation can be found in the doc that comes with this PR: https://github.com/PopulateTools/gobierto/blob/3556c523e1e65d50f5fd9e15762d1ed5a262afcb/docs/dynamic-content-component.md

Any new strings are being localised into the three languages available now. I tried to do my best with the Catalan translations, but once again I'd need some help from my beloved @ferblape. Most of the strings are already localised, but there're some in which I had doubts 😛 

---

### How should this be manually tested?

First, run migrations and re-seed the database to make sure the new `GobiertoPeople` module is reachable via the `madrid.gobierto.dev` Site in the left sidebar.

Having http://gobierto.dev/admin/people/people as the main entry point for this feature, let's check that:

- [x] A Person can be created.
- [x] A Person can be updated.
- [x] New (dynamic content) fields can be added in this context.
- [x] A new Content block can be created.
- [x] A Content block can be updated, by changing its title and any of its fields' properties.
- [x] New fields can be added or deleted in a Content block context.
- [x] A Content block can be deleted as well.
- [x] Everything is localised.
- [x] There's a good test coverage for every new part!

---

#### ✏️ Missing stuff

- Integrate the latest front-end from https://github.com/PopulateTools/gobierto/pull/188.
- Extend the `GobiertoPeople::Person` resource by adding new fields present in the latest specification.
- Limit the Content block management options to privileged Admin users (Manager).
- Continue developing the rest of resources at `Person` level such as Events, Statements and Posts.

### CODE REVIEW

**Comment by danguita** [comment]
@ferblape As we have discussed, this PR is getting huge so I would suggest moving it forward and continue from a clean state. I would say we're ready to close a good first iteration and merge it in case everything goes well. Anyways, it should not have any impact in production until we enable the module in any of the sites available.

Having said that, I'm glad to drop the **wip** label from here so feel free to ask me whatever you need! 🙌

**Comment by ferblape** [comment]
Hey, I've just got an exception creating the first content block.

These are the params of the request:

```
{"utf8"=>"✓",
 "authenticity_token"=>"EK4T7Tyi7U8rv8IFb4svM/ZRX0hwYOAfdTTEb8ij2arpn/dbAEDHMl00X2g9EbCG7FLz8Deg3BG6uEECBfrO8w==",
 "content_block"=>
  {"referrer_url"=>"http://gobierto.dev/admin/people/people/1/edit",
   "content_model_name"=>"GobiertoPeople::Person",
   "title_components_attributes"=>{"0"=>{"locale"=>"es", "value"=>"Datos personales"}, "1"=>{"locale"=>"ca", "value"=>"Dades personals"}},
   "fields_attributes"=>
    {"0"=>{"field_type"=>"text", "label_components_attributes"=>{"0"=>{"locale"=>"es", "value"=>"Nombre"}, "1"=>{"locale"=>"ca", "value"=>"Nom"}}, "_destroy"=>"0"},
     "1483083152814"=>{"field_type"=>"date", "label_components_attributes"=>{"0"=>{"locale"=>"es", "value"=>"Fecha nacimiento"}, "1"=>{"locale"=>"ca", "value"=>"Dada naiximent"}}, "_destroy"=>"0"}}},
 "commit"=>"Crear Bloque de contenido"}
```

This is the error: `undefined method `+' for nil:NilClass`

In the method:
```ruby
    def set_position
      self.position = self.class.maximum(:position) + 1
    end
```

And this is the application trace:

```
app/models/gobierto_common/content_block_field.rb:38:in `set_position'
app/forms/gobierto_admin/gobierto_common/content_block_form.rb:119:in `save_content_block'
app/forms/gobierto_admin/gobierto_common/content_block_form.rb:25:in `save'
app/controllers/gobierto_admin/gobierto_common/content_blocks_controller.rb:40:in `create'
```

**Comment by danguita** [comment]
Yeah, that was a pretty basic case uncovered 🤦‍♂️ It should be fixed now. Thanks for checking!

**Comment by ferblape** [comment]
- All checks completed successfully
- Code review 👌 

As we discussed, we'll wait until we have a newer Postgres version in production to merge it.

Thanks!

**Comment by danguita** [comment]
@ferblape Great! Thanks for the effort 💪

**Pull request merged**
